#!/bin/bash

if [ $(($1 % 2)) -eq 0 ]; then

    printf "DAY $1 BOTH PARTS (RUST)\n"

    pushd "day$1" &> /dev/null
    cargo build --release && printf "\n" && time "./target/release/day$1"
    popd &> /dev/null

else

    printf "DAY $1 (C++)\n"

    if [ "$1" -lt 5 ]; then
        # Before day 5 for cpp day 1 and 2 are separate executables
        parts=${2:-"1,2"}
        for part in $(echo $parts | sed "s/,/ /g") ; do
            printf "PART $part\n"
            g++ --std=c++23 -O3 -Wall -Wextra -pedantic \
                    "day$1/$part/main.cpp" -o "day$1/build/$1$part" \
                && time "./day$1/build/$1$part"
            printf "\n"
        done
    else
        # After day 5 everything is one executatble because it is neater
        g++ --std=c++23 -O3 -Wall -Wextra -pedantic \
                "day$1/src/main.cpp" -o "day$1/build/$1$part" \
            && time "./day$1/build/$1$part"
        printf "\n"
    fi

fi

